stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - data/raw/test.csv
    - data/raw/train.csv
    - src/prepare.py
    params:
    - prepare.random_state
    - prepare.test_size
    - prepare.train_size
    outs:
    - data/processed
